import type { Metadata } from "next";
import { PT_Serif, Fleur_De_Leah } from "next/font/google";
import "./globals.css";

const pt_serif = PT_Serif({
  variable: "--font-pt-serif",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const fleur_de_leah = Fleur_De_Leah({
  variable: "--font-fleur-de-leah",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${pt_serif.variable} ${fleur_de_leah.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
